"""agent executions

Revision ID: 5d024ee07c4d
Revises: 0002_orchestration
Create Date: 2026-08-17 01:40:09.459684
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import forge.db


revision: str = '0003_agent_executions'
down_revision: str | None = '0002_orchestration'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_executions',
    sa.Column('task_id', forge.db.GUID(), nullable=False),
    sa.Column('run_id', forge.db.GUID(), nullable=False),
    sa.Column('project_id', forge.db.GUID(), nullable=False),
    sa.Column('agent_key', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('verification', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', forge.db.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_executions_agent_key'), ['agent_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_executions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_executions_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_executions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_executions_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_executions_task_id'))
        batch_op.drop_index(batch_op.f('ix_agent_executions_status'))
        batch_op.drop_index(batch_op.f('ix_agent_executions_run_id'))
        batch_op.drop_index(batch_op.f('ix_agent_executions_project_id'))
        batch_op.drop_index(batch_op.f('ix_agent_executions_agent_key'))

    op.drop_table('agent_executions')
    # ### end Alembic commands ###
